<?php

$ret='
//NOTE! This file is completely generated by s19tocarray.php script!
//Erase and flash write subroutines to be downloaded into RAM and call them by monitor RUN command.
//See "loader" folder. 
//  Compile: asm8 loader.asm. 
//  Call "php s19tocarray.php loader/loader.s19". 
//    This script re-format data from S19 to C array.
//    Example: S123010055C2A6FFF755C0A606F755C2F655C4F7AE02AD2355C0A60EF7A604AEC8AD184B23
//    Drop out S record identifier (S1), length (23), address (0100) from start of line, and checksum (23) from end of line.
//    Result: 55C2A6FFF755C0A606F755C2F655C4F7AE02AD2355C0A60EF7A604AEC8AD184B
//    Split to bytes.
//    Result: 55 C2 A6 FF F7 55 C0 A6 06 F7 55 C2 F6 55 C4 F7 AE 02 AD 23 55 C0 A6 0E F7 A6 04 AE C8 AD 18 4B
//    Put "0x" before every byte, and separate by coma. 
//    Result: 0x55,0xC2,0xA6,0xFF,0xF7,0x55,0xC0,0xA6,0x06,0xF7,0x55,0xC2,0xF6,0x55,0xC4,0xF7,0xAE,0x02,0xAD,0x23,0x55,0xC0,0xA6,0x0E,0xF7,0xA6,0x04,0xAE,0xC8,0xAD,0x18,0x4B,
//  C array and two routines address are saved into loader.c file by the script.
';
foreach(file($argv[1].".lst") as $line){
  if(preg_match('/\d+\s+([\dA-Fa-f]+)\s+mass_erase\s/',$line,$regs)){
    $ret.="#define MASS_ERASE_ADDRESS 0x".$regs[1]."\n";
    continue;
  }
  if(preg_match('/\d+\s+([\dA-Fa-f]+)\s+write_flash\s/',$line,$regs)){
    $ret.="#define WRITE_ROW_ADDRESS 0x".$regs[1]."\n";
    continue;
  }
}

$ret.="char ram_routines[] = {\n";
foreach(file($argv[1].".s19") as $line){
  $line=trim($line);
  if(substr($line,0,2) != "S1")continue;
  $line=substr($line,8,-2);
  $ret.="  ";
  foreach(str_split($line,2) as $byte){
    $ret.="0x".$byte.",";
  }
  $ret.="\n";
}
$ret=substr($ret,0,-2);//remove last coma
$ret.="\n";
$ret.="};\n";

file_put_contents("loader.c",$ret);
echo "loader.c created successfully.\n";

?>
